build_root:
  image_stream_tag:
    name: ubi-minimal
    namespace: ocp
    tag: "8"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: test-build
  commands: "true"
  container:
    clone: false
    from: root
zz_generated_metadata:
  branch: main
  org: openshift
  repo: openshift-docs
